courses = [
    ('ML0201EN', 'robots are coming  build iot apps with watson  swift  and node red'),
    ('ML0122EN', 'accelerating deep learning with gpu'),
    ('GPXX0ZG0EN', 'consuming restful services using the reactive jax rs client'),
    ('RP0105EN', 'analyzing big data in r using apache spark'),
    ('GPXX0Z2PEN', 'containerizing  packaging  and running a spring boot application'),
    ('CNSC02EN', 'cloud native security conference   data security'),
    ('DX0106EN', 'data science bootcamp with r for university proffesors'),
    ('GPXX0FTCEN', 'learn how to use docker containers for iterative development'),
    ('RAVSCTEST1', 'scorm test 1'),
    ('CC0271EN', 'cloud pak for integration essentials'),
    ('WA0103EN', 'watson analytics for social media'),
    ('DX0108EN', 'data science bootcamp with python for university professors  advance '),
    ('DAI101EN', 'data   ai essentials'),
    ('GPXX0QR3EN', 'enabling distributed tracing in microservices with zipkin'),
    ('BD0145EN', 'sql access for hadoop'),
    ('HCC105EN', 'hybrid cloud conference  ai pipelines lab'),
    ('DE0205EN', 'dataops methodology'),
    ('DS0132EN', 'data   ai  jumpstart your journey'),
    ('OS0101EN', 'introduction to open source'),
    ('DS0201EN', 'end to end data science on cloudpak for data'),
    ('BENTEST4', 'ai for everyone  master the basics'),
    ('CC0210EN', 'serverless computing using cloud functions   developer i'),
    ('PA0103EN', 'predicting customer satisfaction'),
    ('HCC104EN', 'hybrid cloud conference serverless lab'),
    ('TMP0105EN', 'getting started with the data  apache spark makers build'),
    ('PA0107EN', 'predicting financial performance of a company'),
    ('DB0113EN', 'db2 fundamentals i'),
    ('PA0109EN', 'using clustering methods for investment portfolio analysis'),
    ('PHPM002EN', 'php web application on a lamp stack'),
    ('RP0103', 'using r with databases'),
    ('RP0103EN', 'using r with databases'),
    ('BD0212EN', 'spark fundamentals ii'),
    ('SECM03EN', 'apply end to end security to a cloud application'),
    ('SC0103EN', 'spark overview for scala analytics'),
    ('RP0151EN', 'r 101'),
    ('TA0105', 'text analytics 101'),
    ('SW0201EN', 'how to build watson ai and swift apis and make money'),
    ('TMP0106', 'data science bootcamp'),
    ('ST0201EN', 'statistics 201'),
    ('ST0301EN', 'statistics 301'),
    ('SW0101EN', 'build swift mobile apps with watson ai services'),
    ('TMP0101EN', 'text analysis'),
    ('DW0101EN', 'introduction to machine learning with sound'),
    ('BD0143EN', 'using hbase for real time access to your big data'),
    ('WA0101EN', 'watson analytics 101'),
    ('BD0141EN', 'accessing hadoop data using hive'),
    ('CO0401EN', 'beyond the basics  istio and ibm cloud kubernetes service'),
    ('ML0122ENv1', 'accelerating deep learning with gpu'),
    ('BD0151EN', 'text analytics 101'),
    ('TA0106EN', 'text analytics at scale'),
    ('TMP107', 'data science bootcamp with python'),
    ('ML0111EN', 'machine learning with apache systemml'),
    ('CO0201EN', 'container   kubernetes essentials with ibm cloud'),
    ('TA0105EN', 'text analytics 101'),
    ('PA0101EN', 'predictive modeling fundamentals i'),
    ('BC0202EN', 'build an iot blockchain network for a supply chain'),
    ('BC0101EN', 'blockchain essentials'),
    ('BC0201EN', 'ibm blockchain foundation developer'),
    ('BD0223EN', 'exploring spark s graphx'),
    ('AI0111EN', 'game playing ai with swift for tensorflow  s4tf '),
    ('BD0121EN', 'apache pig 101'),
    ('BD0135EN', 'developing distributed applications using zookeeper'),
    ('BD0133EN', 'controlling hadoop jobs using oozie'),
    ('BD0131EN', 'moving data into hadoop'),
    ('BD0115EN', 'mapreduce and yarn'),
    ('BD0211EN', 'spark fundamentals i'),
    ('ST0101EN', 'statistics 101'),
    ('BD0153EN', 'analyzing big data with a spreadsheet ui'),
    ('DP0101EN', 'openrefine 101'),
    ('BD0137EN', 'solr 101'),
    ('ML0120EN', 'deep learning with tensorflow'),
    ('CB0201EN', 'build chatbots with watson assistant'),
    ('CB0105ENv1', 'node red  basics to bots'),
    ('CL0101EN', 'ibm cloud essentials'),
    ('CO0301EN', 'getting started with microservices with istio and ibm cloud kubernetes service'),
    ('DA0201EN', 'data analysis demos'),
    ('DJ0101EN', 'data journalism  first steps  skills and tools'),
    ('CP0101EN', 'mathematical optimization for business problems'),
    ('DB0111EN', 'db2 academic training'),
    ('DB0115EN', 'db2 fundamentals ii'),
    ('COM001EN', 'scalable web applications on kubernetes'),
    ('DA0151EN', 'data analysis using r 101'),
    ('DB0151EN', 'nosql and dbaas 101'),
    ('GPXX0T0FEN', 'project  deploy a serverless app for image processing'),
    ('DS0107', 'data science career talks'),
    ('DS0110EN', 'data science with open data'),
    ('DX0107EN', 'data science bootcamp with python for university professors'),
    ('DS0321EN', 'bitcoin 101'),
    ('DS0105EN', 'data science hands on with open source tools'),
    ('DS0103EN', 'data science methodology'),
    ('LB0109ENv1', 'reactive architecture  distributed messaging patterns'),
    ('LB0111EN', 'reactive architecture  cqrs   event sourcing'),
    ('ML0115EN', 'deep learning 101'),
    ('LB0105ENv1', 'reactive architecture  reactive microservices'),
    ('LB0103ENv1', 'reactive architecture  domain driven design'),
    ('IT0101EN', 'building robots with tjbot'),
    ('CC0250EN', 'building cloud native and multicloud applications'),
    ('BD0101EN', 'big data 101'),
    ('EE0101EN', 'modernizing java ee applications'),
    ('CO0101EN', 'docker essentials  a developer introduction'),
    ('ML0122ENv3', 'accelerating deep learning with gpus'),
    ('LB0107ENv1', 'reactive architecture  building scalable systems'),
    ('CB0101EN', 'build your own chatbots'),
    ('ML0101EN', 'machine learning with python'),
    ('CB0103EN', 'build your own chatbot'),
    ('ML0109EN', 'machine learning   dimensionality reduction'),
    ('ML0101ENv3', 'machine learning with python'),
    ('DA0101EN', 'data analysis with python'),
    ('SC0101EN', 'scala 101'),
    ('CO0193EN', 'hybrid cloud conference   backend services for containers'),
    ('DS0101EN', 'introduction to data science'),
    ('LB0101ENv1', 'reactive architecture  introduction to reactive systems'),
    ('DS0301EN', 'data privacy fundamentals'),
    ('BD0111EN', 'hadoop 101'),
    ('CC0101EN', 'introduction to cloud'),
    ('BD0221EN', 'spark mllib'),
    ('CC0103EN', 'ibm cloud essentials   v3'),
    ('PY0101EN', 'python for data science'),
    ('CC0201EN', 'introduction to containers  kubernetes  and openshift v2'),
    ('BD0123EN', 'simplifying data pipelines with apache kafka'),
    ('DB0101EN', 'sql and relational databases 101'),
    ('DV0151EN', 'data visualization with r'),
    ('DV0101EN', 'data visualization with python'),
    ('ML0103EN', 'digital analytics   regression'),
    ('ML0151EN', 'machine learning with r'),
    ('ML0120ENv2', 'deep learning with tensorflow'),
    ('RP0101EN', 'r for data science'),
    ('CC0150EN', 'building cloud native and multicloud applications'),
    ('ML0120ENv3', 'deep learning with tensorflow'),
    ('SC0105EN', 'data science with scala'),
    ('excourse40', 'exploratory data analysis for machine learning'),
    ('excourse46', 'machine learning'),
    ('excourse47', 'machine learning for all'),
    ('excourse52', 'machine learning data lifecycle in production'),
    ('excourse53', 'deploying machine learning models in production'),
    ('excourse54', 'exploratory data analysis for machine learning'),
    ('excourse69', 'machine learning with big data'),
    ('excourse77', 'natural language processing with attention models'),
    ('excourse84', 'using r for regression and machine learning in investment ')
]