course_by_genre = {'Database': [('RP0105EN', 'analyzing big data in r using apache spark'),
  ('CC0271EN', 'cloud pak for integration essentials'),
  ('BD0145EN', 'sql access for hadoop'),
  ('DE0205EN', 'dataops methodology'),
  ('TMP0105EN', 'getting started with the data  apache spark makers build'),
  ('DB0113EN', 'db2 fundamentals i'),
  ('RP0103', 'using r with databases'),
  ('RP0103EN', 'using r with databases'),
  ('BD0212EN', 'spark fundamentals ii'),
  ('SC0103EN', 'spark overview for scala analytics'),
  ('BD0143EN', 'using hbase for real time access to your big data'),
  ('BD0141EN', 'accessing hadoop data using hive'),
  ('BD0121EN', 'apache pig 101'),
  ('BD0135EN', 'developing distributed applications using zookeeper'),
  ('BD0131EN', 'moving data into hadoop'),
  ('BD0115EN', 'mapreduce and yarn'),
  ('BD0211EN', 'spark fundamentals i'),
  ('BD0137EN', 'solr 101'),
  ('DJ0101EN', 'data journalism  first steps  skills and tools'),
  ('DB0111EN', 'db2 academic training'),
  ('DB0115EN', 'db2 fundamentals ii'),
  ('DB0151EN', 'nosql and dbaas 101'),
  ('BD0101EN', 'big data 101'),
  ('DS0301EN', 'data privacy fundamentals'),
  ('BD0111EN', 'hadoop 101'),
  ('BD0123EN', 'simplifying data pipelines with apache kafka'),
  ('DB0101EN', 'sql and relational databases 101')],
 'Python': [('ML0122EN', 'accelerating deep learning with gpu'),
  ('DX0108EN',
   'data science bootcamp with python for university professors  advance '),
  ('TMP107', 'data science bootcamp with python'),
  ('ML0101EN', 'machine learning with python'),
  ('ML0101ENv3', 'machine learning with python'),
  ('DA0101EN', 'data analysis with python'),
  ('PY0101EN', 'python for data science'),
  ('DV0101EN', 'data visualization with python')],
 'CloudComputing': [('CNSC02EN',
   'cloud native security conference   data security'),
  ('CC0271EN', 'cloud pak for integration essentials'),
  ('WA0103EN', 'watson analytics for social media'),
  ('DS0201EN', 'end to end data science on cloudpak for data'),
  ('CC0210EN', 'serverless computing using cloud functions   developer i'),
  ('HCC104EN', 'hybrid cloud conference serverless lab'),
  ('SECM03EN', 'apply end to end security to a cloud application'),
  ('SW0201EN', 'how to build watson ai and swift apis and make money'),
  ('SW0101EN', 'build swift mobile apps with watson ai services'),
  ('WA0101EN', 'watson analytics 101'),
  ('CO0401EN', 'beyond the basics  istio and ibm cloud kubernetes service'),
  ('CO0201EN', 'container   kubernetes essentials with ibm cloud'),
  ('BC0201EN', 'ibm blockchain foundation developer'),
  ('CL0101EN', 'ibm cloud essentials'),
  ('CO0301EN',
   'getting started with microservices with istio and ibm cloud kubernetes service'),
  ('CC0250EN', 'building cloud native and multicloud applications'),
  ('CC0101EN', 'introduction to cloud'),
  ('CC0103EN', 'ibm cloud essentials   v3'),
  ('CC0150EN', 'building cloud native and multicloud applications')],
 'DataAnalysis': [('RP0105EN', 'analyzing big data in r using apache spark'),
  ('WA0103EN', 'watson analytics for social media'),
  ('TMP0105EN', 'getting started with the data  apache spark makers build'),
  ('PA0109EN', 'using clustering methods for investment portfolio analysis'),
  ('BD0212EN', 'spark fundamentals ii'),
  ('SC0103EN', 'spark overview for scala analytics'),
  ('ST0201EN', 'statistics 201'),
  ('ST0301EN', 'statistics 301'),
  ('TMP0101EN', 'text analysis'),
  ('WA0101EN', 'watson analytics 101'),
  ('BD0223EN', 'exploring spark s graphx'),
  ('BD0211EN', 'spark fundamentals i'),
  ('ST0101EN', 'statistics 101'),
  ('BD0153EN', 'analyzing big data with a spreadsheet ui'),
  ('DP0101EN', 'openrefine 101'),
  ('DA0201EN', 'data analysis demos'),
  ('DJ0101EN', 'data journalism  first steps  skills and tools'),
  ('CP0101EN', 'mathematical optimization for business problems'),
  ('DA0151EN', 'data analysis using r 101'),
  ('DA0101EN', 'data analysis with python'),
  ('DV0151EN', 'data visualization with r'),
  ('DV0101EN', 'data visualization with python'),
  ('ML0103EN', 'digital analytics   regression'),
  ('excourse40', 'exploratory data analysis for machine learning'),
  ('excourse54', 'exploratory data analysis for machine learning'),
  ('excourse84',
   'using r for regression and machine learning in investment ')],
 'Containers': [('GPXX0Z2PEN',
   'containerizing  packaging  and running a spring boot application'),
  ('GPXX0FTCEN',
   'learn how to use docker containers for iterative development'),
  ('CO0401EN', 'beyond the basics  istio and ibm cloud kubernetes service'),
  ('CO0201EN', 'container   kubernetes essentials with ibm cloud'),
  ('COM001EN', 'scalable web applications on kubernetes'),
  ('CO0101EN', 'docker essentials  a developer introduction'),
  ('CO0193EN', 'hybrid cloud conference   backend services for containers'),
  ('CC0201EN', 'introduction to containers  kubernetes  and openshift v2')],
 'MachineLearning': [('ML0122EN', 'accelerating deep learning with gpu'),
  ('DAI101EN', 'data   ai essentials'),
  ('HCC105EN', 'hybrid cloud conference  ai pipelines lab'),
  ('DS0132EN', 'data   ai  jumpstart your journey'),
  ('BENTEST4', 'ai for everyone  master the basics'),
  ('PA0103EN', 'predicting customer satisfaction'),
  ('PA0107EN', 'predicting financial performance of a company'),
  ('TA0105', 'text analytics 101'),
  ('SW0201EN', 'how to build watson ai and swift apis and make money'),
  ('SW0101EN', 'build swift mobile apps with watson ai services'),
  ('TMP0101EN', 'text analysis'),
  ('DW0101EN', 'introduction to machine learning with sound'),
  ('ML0122ENv1', 'accelerating deep learning with gpu'),
  ('BD0151EN', 'text analytics 101'),
  ('TA0106EN', 'text analytics at scale'),
  ('ML0111EN', 'machine learning with apache systemml'),
  ('TA0105EN', 'text analytics 101'),
  ('PA0101EN', 'predictive modeling fundamentals i'),
  ('AI0111EN', 'game playing ai with swift for tensorflow  s4tf '),
  ('ML0120EN', 'deep learning with tensorflow'),
  ('CB0201EN', 'build chatbots with watson assistant'),
  ('ML0115EN', 'deep learning 101'),
  ('IT0101EN', 'building robots with tjbot'),
  ('ML0122ENv3', 'accelerating deep learning with gpus'),
  ('ML0101EN', 'machine learning with python'),
  ('ML0109EN', 'machine learning   dimensionality reduction'),
  ('ML0101ENv3', 'machine learning with python'),
  ('BD0221EN', 'spark mllib'),
  ('ML0151EN', 'machine learning with r'),
  ('ML0120ENv2', 'deep learning with tensorflow'),
  ('ML0120ENv3', 'deep learning with tensorflow'),
  ('excourse40', 'exploratory data analysis for machine learning'),
  ('excourse46', 'machine learning'),
  ('excourse47', 'machine learning for all'),
  ('excourse52', 'machine learning data lifecycle in production'),
  ('excourse53', 'deploying machine learning models in production'),
  ('excourse54', 'exploratory data analysis for machine learning'),
  ('excourse69', 'machine learning with big data'),
  ('excourse77', 'natural language processing with attention models')],
 'ComputerVision': [('GPXX0T0FEN',
   'project  deploy a serverless app for image processing')],
 'DataScience': [('ML0122EN', 'accelerating deep learning with gpu'),
  ('DX0106EN', 'data science bootcamp with r for university proffesors'),
  ('DX0108EN',
   'data science bootcamp with python for university professors  advance '),
  ('DS0201EN', 'end to end data science on cloudpak for data'),
  ('PA0103EN', 'predicting customer satisfaction'),
  ('PA0107EN', 'predicting financial performance of a company'),
  ('TMP0106', 'data science bootcamp'),
  ('ML0122ENv1', 'accelerating deep learning with gpu'),
  ('BD0151EN', 'text analytics 101'),
  ('TA0106EN', 'text analytics at scale'),
  ('TMP107', 'data science bootcamp with python'),
  ('PA0101EN', 'predictive modeling fundamentals i'),
  ('DS0107', 'data science career talks'),
  ('DS0110EN', 'data science with open data'),
  ('DX0107EN', 'data science bootcamp with python for university professors'),
  ('DS0105EN', 'data science hands on with open source tools'),
  ('DS0103EN', 'data science methodology'),
  ('ML0101EN', 'machine learning with python'),
  ('DS0101EN', 'introduction to data science'),
  ('PY0101EN', 'python for data science'),
  ('RP0101EN', 'r for data science'),
  ('SC0105EN', 'data science with scala')],
 'BigData': [('RP0105EN', 'analyzing big data in r using apache spark'),
  ('BD0145EN', 'sql access for hadoop'),
  ('TMP0105EN', 'getting started with the data  apache spark makers build'),
  ('BD0212EN', 'spark fundamentals ii'),
  ('SC0103EN', 'spark overview for scala analytics'),
  ('BD0143EN', 'using hbase for real time access to your big data'),
  ('BD0141EN', 'accessing hadoop data using hive'),
  ('TA0106EN', 'text analytics at scale'),
  ('BD0223EN', 'exploring spark s graphx'),
  ('BD0121EN', 'apache pig 101'),
  ('BD0133EN', 'controlling hadoop jobs using oozie'),
  ('BD0131EN', 'moving data into hadoop'),
  ('BD0115EN', 'mapreduce and yarn'),
  ('BD0211EN', 'spark fundamentals i'),
  ('DB0151EN', 'nosql and dbaas 101'),
  ('BD0101EN', 'big data 101'),
  ('BD0111EN', 'hadoop 101'),
  ('BD0221EN', 'spark mllib'),
  ('excourse69', 'machine learning with big data')],
 'Chatbot': [('CB0201EN', 'build chatbots with watson assistant'),
  ('CB0101EN', 'build your own chatbots'),
  ('CB0103EN', 'build your own chatbot')],
 'BackendDev': [('ML0201EN',
   'robots are coming  build iot apps with watson  swift  and node red'),
  ('GPXX0ZG0EN',
   'consuming restful services using the reactive jax rs client'),
  ('GPXX0Z2PEN',
   'containerizing  packaging  and running a spring boot application'),
  ('GPXX0QR3EN', 'enabling distributed tracing in microservices with zipkin'),
  ('DE0205EN', 'dataops methodology'),
  ('OS0101EN', 'introduction to open source'),
  ('CC0210EN', 'serverless computing using cloud functions   developer i'),
  ('HCC104EN', 'hybrid cloud conference serverless lab'),
  ('PHPM002EN', 'php web application on a lamp stack'),
  ('SECM03EN', 'apply end to end security to a cloud application'),
  ('SW0201EN', 'how to build watson ai and swift apis and make money'),
  ('SW0101EN', 'build swift mobile apps with watson ai services'),
  ('CO0401EN', 'beyond the basics  istio and ibm cloud kubernetes service'),
  ('BC0202EN', 'build an iot blockchain network for a supply chain'),
  ('BC0101EN', 'blockchain essentials'),
  ('BD0135EN', 'developing distributed applications using zookeeper'),
  ('BD0133EN', 'controlling hadoop jobs using oozie'),
  ('BD0137EN', 'solr 101'),
  ('CB0105ENv1', 'node red  basics to bots'),
  ('CO0301EN',
   'getting started with microservices with istio and ibm cloud kubernetes service'),
  ('COM001EN', 'scalable web applications on kubernetes'),
  ('GPXX0T0FEN', 'project  deploy a serverless app for image processing'),
  ('LB0109ENv1', 'reactive architecture  distributed messaging patterns'),
  ('LB0111EN', 'reactive architecture  cqrs   event sourcing'),
  ('LB0105ENv1', 'reactive architecture  reactive microservices'),
  ('LB0103ENv1', 'reactive architecture  domain driven design'),
  ('EE0101EN', 'modernizing java ee applications'),
  ('LB0107ENv1', 'reactive architecture  building scalable systems'),
  ('SC0101EN', 'scala 101'),
  ('CO0193EN', 'hybrid cloud conference   backend services for containers'),
  ('LB0101ENv1', 'reactive architecture  introduction to reactive systems'),
  ('BD0123EN', 'simplifying data pipelines with apache kafka'),
  ('CC0150EN', 'building cloud native and multicloud applications')],
 'FrontendDev': [('ML0201EN',
   'robots are coming  build iot apps with watson  swift  and node red'),
  ('GPXX0ZG0EN',
   'consuming restful services using the reactive jax rs client'),
  ('OS0101EN', 'introduction to open source'),
  ('LB0105ENv1', 'reactive architecture  reactive microservices'),
  ('LB0103ENv1', 'reactive architecture  domain driven design'),
  ('LB0101ENv1', 'reactive architecture  introduction to reactive systems'),
  ('CC0150EN', 'building cloud native and multicloud applications')],
 'Blockchain': [('BC0202EN',
   'build an iot blockchain network for a supply chain'),
  ('BC0101EN', 'blockchain essentials'),
  ('BC0201EN', 'ibm blockchain foundation developer'),
  ('DS0321EN', 'bitcoin 101')],
  'R Language': [('RP0105EN', 'analyzing big data in r using apache spark'),
  ('DX0106EN', 'data science bootcamp with r for university proffesors'),
  ('RP0103', 'using r with databases'),
  ('RP0103EN', 'using r with databases'),
  ('RP0151EN', 'r 101'),
  ('DA0151EN', 'data analysis using r 101'),
  ('DV0151EN', 'data visualization with r'),
  ('ML0151EN', 'machine learning with r'),
  ('RP0101EN', 'r for data science'),
  ('excourse84',
   'using r for regression and machine learning in investment ')]}